### ISSUE TITLE
Checking children's boxes should not check parent's box

### ISSUE THREAD

**Issue by nabn** [ArriaOpenSource/ng2-tree#2]
" In a scenario where I add a folder under an empty folder, I will not be able to add anything under this because if I select the subset folder/main folder, both the folders get selected and the add buttons are no more available"

**Comment by renaldas-kerpe-arria** [comment]
This does not sound like a correct behaviour. If all the children are checked, I would expect the parent to get checked too. What about adding options to create new script/folder to the context menu?

**Comment by renaldas-kerpe-arria** [comment]
Implemented as a configurable option in NSAT-775 branch.
