### ISSUE TITLE
Make context menu show up in visible space and not get hidden below the footer

### ISSUE THREAD

**Issue by nabn** [ArriaOpenSource/ng2-tree#3]
<img width="347" alt="screen shot 2018-11-15 at 11 24 32 am" src="https://user-images.githubusercontent.com/1693287/48521559-13058700-e8c9-11e8-9bf6-beef22d7c3e7.png">

**Comment by renaldas-kerpe-arria** [comment]
This might be a bit tricky, and could require some refactoring. I think the menu is still usable, just need to scroll down a bit. There are few showstopper issues that I need to deal with first, but will take a look at this after. 

Also, PRs are welcome 😃.

**Comment by renaldas-kerpe-arria** [comment]
Fixed in NSAT-775 branch.
