### ISSUE TITLE
Add support for double click event

### ISSUE THREAD

**Issue by nabn** [ArriaOpenSource/ng2-tree#6]

**Comment by nabn** [comment]
@renaldas-kerpe-arria Please review when you get a chance.

**Comment by renaldas-kerpe-arria** [comment]
This should be simple enough. Should this be just a generic event emitted from the tree that contains the node that was clicked, or do we want it to do some specific action? I think I read somewhere that we want the double click to start editing a node?

**Comment by renaldas-kerpe-arria** [comment]
Deleted my previous comment as I just noticed you've already implemented this. I will ask someone here to create a PR for your branch, review that and pull into 775, then merge 775 into master, tag it and pull into NSAT-683.

**Comment by renaldas-kerpe-arria** [comment]
Merged into NSAT-775, which will be merged into master next.
